strcpy(cmds[0].name, "cat");
cmds[0].func = &_cat;
strcpy(cmds[1].name, "cd");
cmds[1].func = &_cd;
strcpy(cmds[2].name, "echo");
cmds[2].func = &_echo;
strcpy(cmds[3].name, "help");
cmds[3].func = &_help;
strcpy(cmds[4].name, "ls");
cmds[4].func = &_ls;
strcpy(cmds[5].name, "pwd");
cmds[5].func = &_pwd;
strcpy(cmds[6].name, "quit");
cmds[6].func = &_quit;
strcpy(cmds[7].name, "whoami");
cmds[7].func = &_whoami;
